server {
    listen 80;
    server_name localhost;

    client_max_body_size 100M;
    root /usr/share/nginx/html;
    index index.html;

    # عشان صفحات React تشتغل صح وماتجبش 404
    location / {
        try_files $uri $uri/ /index.html;
    }

    # كل requests بتروح لـ /api/ تتحول للباك إند
    location /api/ {
        # استخدمنا اسم الكونتينر الصريح
        proxy_pass http://security_portal_backend:3000/;
        
        # الإعدادات السحرية اللي Go Fiber بيحبها
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # ضغط الملفات عشان الموقع يفتح أسرع
    gzip on;
    gzip_types text/plain text/css application/json application/javascript;
}